on:
  workflow_dispatch

jobs:
  generate:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Setup dotnet dependencies
        run: dotnet tool install --global CSharpToTypeScript.CLITool

      - name: Generate typescript
        run: dotnet cs2ts

      - name: Generate typescript
        run: ls -la ./render/

      - name: List all
        run: |
          search_dir=./render
          for entry in "$search_dir"/*
          do
            echo "\n $entry\n"
            cat $entry
          done

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@roog'
  
      #- run: npm ci
      - run: npm publish
        working-directory: ./render
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Generate typescript
#        run: dotnet cs2ts --help


      #- run: dotnet build <my project>
      # cs2tsconfig.json
